//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Admin_Id { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Username { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Phone { get; set; }
        public int User_Type { get; set; }
        public string Admin_Type { get; set; }
    }
}
