//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EhutBazardbEntities : DbContext
    {
        public EhutBazardbEntities()
            : base("name=EhutBazardbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Affiliator> Affiliators { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Notice> Notices { get; set; }
        public DbSet<Request_Shopowner> Request_Shopowner { get; set; }
        public DbSet<Shop_Product> Shop_Product { get; set; }
        public DbSet<ShopOwner> ShopOwners { get; set; }
        public DbSet<Token> Tokens { get; set; }
    }
}
