//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int Notice_Id { get; set; }
        public string Notice_Post { get; set; }
        public string Post_Date { get; set; }
        public int Admin_Id { get; set; }
    }
}
