//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Shopowner
    {
        public int ShopO_Id { get; set; }
        public string ShopO_Name { get; set; }
        public string ShopO_Username { get; set; }
        public string ShopO_Password { get; set; }
        public string ShopO_Email { get; set; }
        public string ShopO_Phone { get; set; }
        public string ShopO_Shopname { get; set; }
        public string ShopO_Description { get; set; }
        public int User_Type { get; set; }
    }
}
