//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public string AccessToken { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string UserType { get; set; }
    }
}
